### ISSUE TITLE
Check best way to set root logger

### ISSUE THREAD

**Issue by gabrielgflower** [jonathadv/django-logger-panel#5]
As [django docs](https://docs.djangoproject.com/en/3.2/topics/logging/) does, maybe we could set directly the root logger instead of having an empty key.
Seems like it works just as same and feels less confusing.
`        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },`
instead of
`            'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },`

**Comment by gabrielgflower** [comment]
> As [django docs](https://docs.djangoproject.com/en/3.2/topics/logging/) does, maybe we could set directly the root logger instead of having an empty key.
> Seems like it works just as same and feels less confusing.
> ` 'root': { 'handlers': ['console'], 'level': 'INFO', },`
> instead of
> ` 'loggers': { 'root': { 'handlers': ['console'], 'level': 'INFO', }, },`

**Comment by jonathadv** [comment]
Good point!

Feel free to open a PR fixing the README.me by adding this information and the Django's official reference.

**Comment by gabrielgflower** [comment]
Fix #6

**Comment by gabrielgflower** [comment]
PR for fix #6
